### ISSUE TITLE
adapt edown to OTP 18 rc1

### ISSUE THREAD

**Issue by uwiger** [uwiger/edown#4]
Got reports that edoc changes in 18 rc1 affect edoc:
```
commit 6f492b98505ee6d68b9f438915dfbd3616a1b729
Author: Vlad Dumitrescu <vladdu55@gmail.com>
Date:   Fri Jan 16 09:39:31 2015 +0100

    [edoc] remove functionality related to packages
    
    The 'subpackages' option is left, since some projects use recursive
    source directories.
```

**Comment by nettod** [comment]
I just upgraded to 18. edown now fails to compile:

Compiling /blah/deps/edown/src/edown_doclet.erl failed:
/blah/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/blah/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen

I am tempted to remove all references to these fields. Is there a fix for it yet?

**Comment by uwiger** [comment]
The latest version (tagged 0.7) should work with 18.0.

**Comment by nettod** [comment]
Works great. Thank you!
